services:
- docker
dist: xenial

script: bash travis_docker.sh build

deploy:
  provider: script
  script: bash travis_docker.sh push
  on:
    branch: master

matrix:
  include:
    - env: IMAGE=debian-unstable
    - env: IMAGE=ubuntu-xenial
    - env: IMAGE=windows-mxe
    - env: IMAGE=mac-osxcross
