services:
- docker
dist: xenial

script: bash travis_docker.sh build

deploy:
  provider: script
  script: bash travis_docker.sh push
  on:
    branch: master

matrix:
  include:
    - env: IMAGE=debian-unstable
    - env: IMAGE=ubuntu-trusty
    - env: IMAGE=ubuntu-touch-xenial
    - env: IMAGE=neon-bionic
    - env: IMAGE=archlinux
