FROM archlinux/base

RUN pacman -Sy && \
    pacman -S --noconfirm \
        qt5-base \
        qt5-declarative \
        qt5-quickcontrols2 \
        kirigami2 \
        gloox \
        cmake \
        ccache \
        appstream \
        extra-cmake-modules \
	ninja \
        qt5-tools \
        base-devel \
        qt5-svg \
        libidn
