FROM debian:unstable

RUN apt update && \
    apt install -y \
        cmake \
        ninja-build \
        kirigami2-dev \
        build-essential \
        extra-cmake-modules \
        qtbase5-dev \
        qt5-default \
        qttools5-dev \
        qtquickcontrols2-5-dev \
        libgloox-dev \
        qtdeclarative5-dev \
        libqt5svg5-dev \
        ccache \
        mesa-common-dev \
        libgl1-mesa-dev \
        libssl-dev
